config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:index, :show, :edit, :update]

  root to: 'homes#top'
  get "/home/about" => 'homes#about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, length: {in: 2..20}, uniqueness: true
  #
  validates :introduction , length: {maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  # def get_profile_image
  #   (profile_image.attached?) ? profile_image : 'no_image.jpg'
  # end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)

    user_path(current_user.id)
  end

  def after_sign_up_path_for(resource)

    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    "/"
  end

  protected

#   def configure_permitted_parameters
#     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
#   end


  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @nbook = Book.new
  end

  def create
    @user = current_user
    @nbook = Book.new(book_params)
    @nbook.user_id = current_user.id
    if @nbook.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@nbook.id)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @nbook = Book.new
    # @book = Book.find(params[:id])

  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @nbook = Book.new

    # @user = current_user
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!


  def index
    @users = User.all
    @nbook = Book.new
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @nbook = Book.new
    @books = Book.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user.id)
    end

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
  <% if nbook.errors.any? %>
    <%= nbook.errors.count %>errors prohibited this obj from being saved:
    <ul>
      <% nbook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

<h1>New book</h1>
  <%= form_with model: nbook do |f| %>
    <h4>Title</h4>
      <%= f.text_field :title %>
    <h4>Opinion</h4>
      <%= f.text_area :body %>
    <%= f.submit 'Create Book' %>
  <% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit "Update Book" %>

  <span>
    <%= link_to "Show", book_path(@book.id) %>
  </span>
  <span>
    <%= link_to "Back", "/books" %>
  </span>

<% end %>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3" style="background-color: gray">
      <%= render 'users/list', user: @user %>
      <%= render 'list', nbook: @nbook %>
    </div>
<!--book: @book-->
    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class="table table-striped">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
        <% @books.each do |book| %>
        <tr>
          <td>
              <%= link_to user_path(book.user.id) do %>
                <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
          </td>
          <td><%= book.body %></td>
        </tr>
        <% end %>
      </table>


    </div>
  </div>
</div>

app/views/books/new.html.erb
<%= render 'list', book: @book %>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3" style="background-color: gray">
      <%= render 'users/list', user: @user %>
      <%= render 'list', book: @book, nbook: @nbook %>
    </div>

    <div class="col-md-8 offset-md-1">
      <%= flash[:notice] %>
      <h1>Book detail</h1>
      <table class="table table-striped">
        <tr>
          <td>
            <%= link_to user_path(@book.user.id) do %>
              <%= image_tag @book.user.get_profile_image(100,100) %>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to edit_book_path(@book) do %>
              <%= @book.title %>
            <% end %>
          </td>
          <td>
            <%= @book.body %>
          </td>
          <% if @book.user == current_user %>
          <td>
            <%= link_to "Edit", edit_book_path %>
          </td>
          <td>
            <%= link_to "Destroy", book_path(@book), method: :delete %>
          </td>

        </tr>
        <% end %>
      </table>

    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
    <div class="row">
            <h1>Welcome to</h1><i class="fas fa-book"></i><h1>Bookers!</h1>
    </div>
</div>

app/views/homes/top.html.erb
<h1>Welcome to</h1><i class="fas fa-book"></i><h1>Bookers!!</h1>
<h4>In</h4><i class="fas fa-book"></i><h4>Bookers.</h4>
<p>you can share and exchange your opinions, inpressions, and emotions<br>
about various books!</p>

<%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
<%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container" style="background-color: #343a40">
        <div class="row">
      <% if user_signed_in? %>
      <span class="col-md-4">
        <%= link_to "Bookers", "/" %>
      </span>

        <ul class="col-md-8 nav justify-content-end">
          <li>
            <%= link_to user_path(current_user.id) do %>
              <i class="fas fa-home"></i>Home
            <% end %>
          </li>
          <li>
            <%= link_to users_path do %>
              <i class="fas fa-users"></i>Users
            <% end %>
          </li>
          <li>
            <%= link_to books_path do %>
              <i class="fas fa-book-open"></i>Books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt"></i>Log out
            <% end %>
          </li>
        </ul>
        <!--<li>%= link_to "投稿フォーム", new_book_path %></li>-->


      <% else %>
        <span class="col-md-4">
          <%= link_to "Bookers", "/" %>
        </span>


        <ul class="col-md-8 nav justify-content-end">
          <li>
            <%= link_to "/" do %>
              <i class="fas fa-home"></i>Home
            <% end %>
          </li>
          <li>
            <%= link_to about_path do %>
              <i class="fas fa-link"></i>About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path do %>
              <i class="fas fa-user-plus"></i>Sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path do %>
              <i class="fas fa-sign-in-alt"></i>Log in
            <% end %>
          </li>
        </ul>
      <% end %>
      </div>
    </header>
    </div>

    <%= notice %>
    <%= yield %>
    <footer>
        <div class="text-center">
          CopyRight Infratop.inc
        </div>
    </footer>
  </body>
</html>

app/views/users/_list.html.erb
<div>

  <h3>User info</h3>
  <%= image_tag user.get_profile_image(100,100) %>
  <h3>name</h3>
  <%= user.name %>
  <h3>introduction</h3>
  <%= user.introduction %>
  <!--% if user.id == current_user.id %>-->
    <%= link_to edit_user_path(user), class: "btn btn-denger", method: :get do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <!--% else %>-->
    <!--%= link_to user_path(current_user.id), class: "btn btn-denger", method: :get do %>-->
    <!--  <i class="fas fa-user-cog"></i>-->
    <!--% end %>-->
  <!--% end %>-->
</div>

app/views/users/edit.html.erb
    <% if @user.errors.any? %>
    <%= @user.errors.count %>error prohibited this obj from being saved:
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<h2>User info</h2>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"紹介文を入力" %>

  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div class="container">
    <div class="row">
            <div class="col-md-3" style="background-color: gray">
                <%= render 'list', user: @user %>
                <%= render 'books/list', book: @book, nbook: @nbook %>
            </div>

<!--get_profile_image-->
            <div class="col-md-8 offset-md-1">
                <h1>Users</h1>
                <table class="table table-striped">
                    <tr>
                        <th>image</th>
                        <th>name</th>
                        <th></th>
                    <% @users.each do |user| %>
                    <tr>
                            <td>
                                <%= image_tag user.get_profile_image(100,100) %>
                            </td>
                        <td><%= user.name %></td>
                        <td><%= link_to "Show", user_path(user.id) %></td>
                    </tr>
                <% end %>
                </table>
            </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
            <div class="col-md-3" style="background-color: gray">
                <%= render 'list', user: @user %>
                <%= render 'books/list', book: @book, nbook: @nbook %>
            </div>


            <div class="col-md-8 offset-md-1">
<!-- ユーザーの投稿一覧 -->
              <%= flash[:alart] %>
              <h1>Books</h1>
              <table class="table table-striped">
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                </tr>


              <% @books.each do |book| %>
                    <% if book.user_id == @user.id %>
                <tr>
                  <td>
                    <%= link_to user_path(book.user.id) do %>
                      <%= image_tag book.user.get_profile_image(100,100) %>
                    <% end %>
                  </td>
                  <td>

                      <%= link_to book_path(book.id) do %>
                        <%= book.title %>
                      <% end %>

                  </td>
                  <td><%= book.body %></td>
                    <% end %>
                </tr>
              <% end %>
              </table>


            </div>
    </div>
</div>